
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:

  type-aliases-package: com.hsds.demo.mapper

  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      hsds:
        demo:
          Dao: debug
server:
  port: 80

#编码格式
server.tomcat.uri-encoding: utf-8


#session生命周期
server.servlet.session.timeout: 30m
